
x80sv:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

  left_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_as
    pid: {p: 0.0005, i: 0.5, d: 0.0, i_clamp: 10.0}

  right_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_as
    pid: {p: 0.0005, i: 0.5, d: 0.0, i_clamp: 10.0}
