<?xml version="1.0"?>

<robot
xmlns:xacro="http://www.ros.org/wiki/xacro"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

    <!-- Included URDF Files -->
    <xacro:include filename="$(find erratic_description)/urdf/materials.urdf.xacro" />
    <xacro:include filename="$(find erratic_description)/urdf/erratic_computer.xacro" />
    <xacro:include filename="$(find erratic_description)/urdf/erratic_wheel.xacro" />

    <property name="base_link_to_top" value="0.0795" />
    <property name="base_link_to_front" value="0.2025" />
    <property name="base_link_to_back" value="0.1975" />

<macro name="erratic">
        <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
             navigation stack depends on this frame -->
        <link name="base_footprint">
            <inertial>
                <mass value="0.0001" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                         iyy="0.0001" iyz="0.0" 
                         izz="0.0001" />
            </inertial>
            
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
                <material name="Green" />
            </visual>
            
            <collision>
                <origin xyz="0 0 0.128" rpy="0 0 0" />
                <geometry>
                  <box size="0.001 0.001 0.001" />
                </geometry>
            </collision>
        </link>

        <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0.063 0 0.128" rpy="0 0 0" />
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>

        <!-- Links and Joints (i.e., the robot) -->
        <link name="base_link">
            <inertial>
                <mass value="20" />
                <origin xyz="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://erratic_description/meshes/collada/erratic_base_link.dae"/>
                </geometry>
                <material name="Blue" />
            </visual>
            
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://erratic_description/meshes/collada/erratic_base_link.dae"/>
                </geometry>
            </collision>
        </link>

        <joint name="base_caster_support_joint" type="continuous">
            <origin xyz="-0.188 0 -0.043" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="base_caster_support_link"/>
            
            <axis xyz="0 0 1" />
            <anchor xyz="0.01 0 0" />
            <limit effort="100" velocity="100" k_velocity="0" />
            <joint_properties damping="0.0" friction="0.0" />
        </joint>

        <transmission type="pr2_mechanism_model/SimpleTransmission" name="base_caster_support_trans">
            <actuator name="base_caster_support_motor" />
            <joint name="base_caster_support_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>

        <link name="base_caster_support_link">
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0" />
                <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                         iyy="0.01" iyz="0.0"
                         izz="0.01" />
            </inertial>
            
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://erratic_description/meshes/collada/erratic_caster_support_link.dae"/>
                </geometry>
            </visual>
            
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://erratic_description/meshes/collada/erratic_caster_support_link.dae"/>
                </geometry>
            </collision>
        </link>

        <joint name="caster_wheel_joint" type="continuous">
            <origin xyz="-0.025 0 -0.0469" rpy="0 0 0" />
            <parent link="base_caster_support_link" />
            <child link="caster_wheel_link" />
            
            <axis xyz="0 1 0" />
            <anchor xyz="0 0 0" />
            <limit effort="100" velocity="100" k_velocity="0" />
            <joint_properties damping="0.0" friction="0.0" />
        </joint>

        <transmission type="pr2_mechanism_model/SimpleTransmission" name="caster_wheel_trans">
            <actuator name="caster_wheel_motor" />
            <joint name="caster_wheel_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>

        <link name="caster_wheel_link">
            <inertial>
                <mass value="0.1" /> 
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                          iyy="0.015218160428" iyz="-0.000004273467"
                          izz="0.011763977943" />
            </inertial>
            
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://erratic_description/meshes/collada/erratic_caster_wheel_link.dae"/>
                </geometry>
                <material name="Black"/>
            </visual>
            
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://erratic_description/meshes/collada/erratic_caster_wheel_link.dae"/>
                </geometry>
            </collision>
        </link>

        <gazebo reference="caster_wheel_link">
            <mu1 value="100.0" />
            <mu2 value="100.0" />
            <kp  value="1000000.0" />
            <kd  value="1.0" />
        </gazebo>


        <!-- MACRO INSTANTIATION -->

        <erratic_computer parent="base_link">
            <origin xyz="${-base_link_to_back + computer_size_x/2 + 0.02} 0 ${base_link_to_top}" rpy="0 0 0" />
        </erratic_computer>
        
        <erratic_wheel suffix="left" parent="base_link">
            <origin xyz="0.075 0.16525 -0.053" rpy="0 0 0" />
        </erratic_wheel>
        
        <erratic_wheel suffix="right" parent="base_link">
            <origin xyz="0.075 -0.16525 -0.053" rpy="0 0 0" />
        </erratic_wheel>


        <!-- CONTROLLERS -->

        <gazebo>
            <controller:diffdrive_plugin name="differential_drive_controller" plugin="libdiffdrive_plugin.so">
                <alwaysOn>true</alwaysOn>
                <update>100</update>
                <updateRate>100.0</updateRate>
                <leftJoint>base_link_right_wheel_joint</leftJoint>
                <rightJoint>base_link_left_wheel_joint</rightJoint>
                <wheelSeparation>0.3305</wheelSeparation>
                <wheelDiameter>0.15</wheelDiameter>
                <torque>5</torque>
                <interface:position name="position_iface_0"/>
                <topicName>cmd_vel</topicName>
            </controller:diffdrive_plugin>

            <controller:gazebo_ros_p3d name="p3d_base_controller" plugin="libgazebo_ros_p3d.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <bodyName>base_link</bodyName>
                <topicName>base_pose_ground_truth</topicName>
                <gaussianNoise>0.01</gaussianNoise>
                <frameName>map</frameName>
                <xyzOffsets>0 0 0</xyzOffsets> 
                <rpyOffsets>0 0 0</rpyOffsets>
                <interface:position name="p3d_base_position"/>
            </controller:gazebo_ros_p3d>

            <canonicalBody>base_footprint</canonicalBody>

            <!-- this publishes empty joint_states due to no transmission, but
             triggering robot_state_publisher to publish tf between fixed joints in erratic,
             (e.g. base_laser_link for the base_scan frame) -->
            <controller:gazebo_ros_controller_manager name="gazebo_ros_controller_manager" plugin="libgazebo_ros_controller_manager.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <interface:audio name="gazebo_ros_controller_manager_dummy_iface" />
            </controller:gazebo_ros_controller_manager>
        </gazebo>

        <!-- GAZEBO MATERIALS -->

        <gazebo reference="base_link">
            <material>Erratic/Blue</material>
        </gazebo>
        
        <gazebo reference="base_top_link">
            <material>Erratic/Blue</material>
        </gazebo>
        
        <gazebo reference="caster_wheel_link">
            <material>Erratic/Black</material>
        </gazebo>
        
        <gazebo reference="base_caster_box_link">
            <material>Erratic/Black</material>
        </gazebo>
        
        <gazebo reference="base_caster_support_link">
            <material>Erratic/White</material>
        </gazebo>
    </macro>
</robot>
